### ISSUE TITLE
Illumination vs Dynamic Illumination

### ISSUE THREAD

**Issue by dmferd** [delVhariant/illumination#27]
Hello
I have Illumination installed on my Forge version of Foundry and Dynamic Illumination on my PC version. When I use the forge version and it is daylight the PC tokens see in full colour but when I use Dynamic Illumination on my PC version the PC tokens se in greyscale even in full daylight.  Are these two modules different or are they the same?

**Comment by delVhariant** [comment]
Hi @dmferd, I'm not sure if the Forge module is the same one, possibly it's just using the repo name instead of the module name, which would make sense, although I'm not sure what release it would be using.

With regards to the problem you're having on your PC, I've just pushed a new update that's compatible with 0.7.9, can you confirm if you're still having issues?

**Comment by dmferd** [comment]
Hello

 

The problem is fixed.

 

Thank you

 

Joel
